########################################
# HTML
########################################

[[plugins]]
# HTML5のシンタックスハイライト
repo = 'othree/html5.vim'
on_ft = ['html']

########################################
# CSS
########################################

[[plugins]]
# CSS3のシンタックスハイライト
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'less', 'sass']

########################################
# Javascript
########################################

[[plugins]]
# JSのシンタックスハイライト
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

########################################
# Python
########################################

[[plugins]]
# pep8による自動修正
repo = 'tell-k/vim-autopep8'
on_ft = ['python']

########################################
# markdown
########################################

[[plugins]]
# Markdownのシンタックスハイライト
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
# Markdownのプレビュー
repo = 'kannokanno/previm'
on_ft = ['markdown']
