########################################
# HTML
########################################

[[plugins]]
# HTML5のシンタックスハイライト
repo = 'othree/html5.vim'
on_ft = ['html']

########################################
# CSS
########################################

[[plugins]]
# CSS3のシンタックスハイライト
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'less', 'sass']

########################################
# Javascript
########################################

[[plugins]]
# JSのシンタックスハイライト
repo = 'jelera/vim-javascript-syntax'
on_ft = ['javascript']

########################################
# Python
########################################

[[plugins]]
# pep8による自動修正
repo = 'tell-k/vim-autopep8'
on_ft = ['python']
hook_add = ''' " {{{
  function! Preserve(command)
      " Save the last search.
      let search = @/
      " Save the current cursor position.
      let cursor_position = getpos('.')
      " Save the current window position.
      normal! H
      let window_position = getpos('.')
      call setpos('.', cursor_position)
      " Execute the command.
      execute a:command
      " Restore the last search.
      let @/ = search
      " Restore the previous window position.
      call setpos('.', window_position)
      normal! zt
      " Restore the previous cursor position.
      call setpos('.', cursor_position)
  endfunction

  function! Autopep8()
      call Preserve(':silent %!autopep8 -')
  endfunction

  autocmd FileType python nnoremap <S-f> :call Autopep8()<CR>
''' # }}}

########################################
# markdown
########################################

[[plugins]]
# Markdownのシンタックスハイライト
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
# Markdownのプレビュー
repo = 'kannokanno/previm'
on_ft = ['markdown']
hook_add = ''' " {{{
  let g:previm_open_cmd = 'open'
''' # }}}
